test:
  adapter: postgresql
  encoding: unicode
  database: DP
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: DP
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: somedatabase_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

